image: ghcr.io/remvze/moodist

tag: latest

env: testing

cluster:
  name: k8s
  domain: cluster.local

datacenter: dc1

region: yxl

gateway:
  name: main-gw
  namespace: core-prod
  sectionName: https-myloginspace
