# yaml-language-server: $schema=./values.schema.json
env: testing

gateway:
  name: main-gw
  namespace: core-prod
  sectionName: https-myloginspace

cluster:
  name: k8s
  domain: cluster.local

datacenter: dc1

region: yxl

crossplane:
  userCreation:
    enabled: true

    providers:
      psql:
        terraformProvider: psql
        crossplaneProvider: psql-main
      s3:
        terraformProvider: s3-yvr-home1-core
        crossplaneProvider: s3-yvr-home1-core

secrets:
  enabled: true

  rootPrefix: n8n/testing

  secretStoreRef:
    kind: ClusterSecretStore
    name: mainvault-core

n8n:
  enabled: true

  db:
    type: postgresdb

  worker:
    mode: queue

  strategy:
    type: RollingUpdate


  externalRedis:
    database: 189
    port: 6379
    username: default
    existingSecret: n8n-core-redis-secret

    tls:
      enabled: true 

  externalPostgresql:
    port: 5432

    existingSecret: n8n-core-psql-secret